#!/usr/bin/env python3
"""
Weber
"""

import sys, readline, re, random
from source import log
from source import lib

lib.reload_config()

from source import weber
from source import commands
from source.proxy import *
from source.lib import exit_program

# get first target
try:
    init_target = sys.argv[1]
except:
    log.err('Usage: %s example.com' % (sys.argv[0]))
    exit_program(-1, None)


# motd
log.newline()
log.info(weber.motd[random.randint(0, len(weber.motd)-1)])

# start proxy
weber.proxy = Proxy(init_target)
weber.proxy.start()

while True:
    # get command
    try:
        cmd = input(log.prompt).strip()
    except EOFError: # Ctrl+D -> quit
        log.newline()
        lib.exit_program(None, None)
    if len(cmd) == 0:
        continue
    # quit?
    if lib.quitstring(cmd):
        log.warn('Do you really want to quit? ', new_line=False)
        if lib.positive(input()):
            lib.exit_program(None, None)
    # do command
    else:
        commands.run_command(cmd)

