#!/usr/bin/env python3

from source import weber
from source.proxy import *
from source import lib
from source import commands
from source import log
from source.lib import exit_program
import sys
import readline
import re

try:
    init_target = sys.argv[1]
except:
    log.err('Usage: %s example.com' % (sys.argv[0]))
    exit_program(-1, None)

commands.reload_config()

weber.proxy = Proxy(init_target)
weber.proxy.start()

############################
# TEST
test_uris = [
    'seznam.cz',
    'https://google.com',
    'ws-dev.vsb.cz/admin',
    'https://jabber.vsb.cz:9091',
    'https://jabber.vsb.cz:9091/',
    '89.29.123.45:443/wp-admin',
    'https://www.seznam.cz/',
    'https://user:pass@server.cz:22/path/file.txt',
    '',
]
#for test_uri in test_uris:
#    print(test_uri, ':', ProxyLib.parse_uri(test_uri, form=str))

# END TEST
############################

while(True):
    # get command
    cmd = input(log.prompt).strip()
    if len(cmd) == 0:
        continue
    # quit?
    if lib.quitstring(cmd):
        log.warn('Do you really want to quit? ', newline=False)
        if lib.positive(input()):
            lib.exit_program(None, None)
    else:
        # do command
        commands.run_command(cmd)

